name: ml-exoplanets
channels:
- conda-forge
dependencies:
- python=3.6.4
- numpy<1.17
- scipy
- pandas=0.22.0
- xlrd=1.1.0
- matplotlib=2.0.2
- tensorflow=1.12.0
- seaborn=0.8
- scikit-learn=0.19.0
- ipython=6.2.1
- notebook=5.7
- requests=2.22
- pillow=4.2.1
- graphviz=2.38.0
- python-graphviz=0.8.4
- pip=18.0
- cython=0.28.4
- astropy=3.2.1
- astroquery=0.3.10 